# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom

Arquivos da aula: https://drive.google.com/drive/folders/1FbDqVq4XLvU85VBlVIMJ73p9oOu6u2-J?usp=drive_link

In [1]:
%pip install pandas scikit-learn

^C
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\thiag\appdata\roaming\python\python312\site-packages (2.2.3)
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thiag\appdata\roaming\python\python312\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thiag\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thiag\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\thiag\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\thiag\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.1 MB 4.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.1 MB 4.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.1 MB 4.4 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/11.1 MB 4.6 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.1 MB 4.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.1 MB 4.9 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.1 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.1 MB 4.3 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.1 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.1 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 3.8 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp312-cp312-win_amd64.whl (40.9 MB)
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
    --------------------------------------- 0.5/40.9 MB 3.4 MB/s eta 0:00:13
   - -------------------------------------- 1.3/40.9 MB 3.1 MB/s eta 0:00:13
   -- ------------------------------------- 2.1/40.9 MB 3.1 MB/s eta 0:00:13
   -- ------------------------------------- 2.9/40.9 MB 3.4 MB/s eta 0:00:12
   --- ------------------------------------ 3.7/40.9 MB 3.5 MB/s eta 0:00:11
   ---- ----------------------------------- 4.7/40.9 MB 3.6 MB/s eta 0:00:11
   ----- ---------------------------------- 5.5/40.9 MB 3.7 MB/s eta 0:00:10
   ----- ---------------------------------- 6.0/40.9 MB 3.5 MB/s eta 0:00:10
   ------ --------------------------------- 6.8/40.9 MB 3.5 MB/s eta 0:00:10
   ------ --------------------------------- 7.1/40.9 MB 3.4 MB/s eta 0:00:10
   ------- -------------------------------- 7.9/40.9 MB 3.4 MB/s eta 0:00:10
   -------- ------------------------------- 8.4/40.9 MB 3.3 MB/s eta 0:00:10
   -------- ------------------------------- 8.9/40.9 MB 3.3 MB/s eta 0:00:10
   --------- ------------------------------ 9.7/40.9 MB 3.3 MB/s eta 0:00:10
   --------- ------------------------------ 10.2/40.9 MB 3.3 MB/s eta 0:00:10
   ---------- ----------------------------- 10.7/40.9 MB 3.2 MB/s eta 0:00:10
   ----------- ---------------------------- 11.5/40.9 MB 3.2 MB/s eta 0:00:10
   ----------- ---------------------------- 12.1/40.9 MB 3.1 MB/s eta 0:00:10
   ------------ --------------------------- 12.6/40.9 MB 3.1 MB/s eta 0:00:10
   ------------- -------------------------- 13.4/40.9 MB 3.1 MB/s eta 0:00:09
   ------------- -------------------------- 13.6/40.9 MB 3.0 MB/s eta 0:00:09
   ------------- -------------------------- 14.2/40.9 MB 3.0 MB/s eta 0:00:09
   -------------- ------------------------- 14.7/40.9 MB 3.0 MB/s eta 0:00:09
   -------------- ------------------------- 15.2/40.9 MB 3.0 MB/s eta 0:00:09
   --------------- ------------------------ 16.0/40.9 MB 3.0 MB/s eta 0:00:09
   ---------------- ----------------------- 16.5/40.9 MB 3.0 MB/s eta 0:00:09
   ---------------- ----------------------- 17.0/40.9 MB 2.9 MB/s eta 0:00:09
   ----------------- ---------------------- 17.6/40.9 MB 2.9 MB/s eta 0:00:08
   ----------------- ---------------------- 18.1/40.9 MB 2.9 MB/s eta 0:00:08
   ------------------ --------------------- 18.6/40.9 MB 2.9 MB/s eta 0:00:08
   ------------------ --------------------- 19.1/40.9 MB 2.9 MB/s eta 0:00:08
   ------------------- -------------------- 19.9/40.9 MB 2.9 MB/s eta 0:00:08
   ------------------- -------------------- 20.2/40.9 MB 2.9 MB/s eta 0:00:08
   -------------------- ------------------- 20.7/40.9 MB 2.9 MB/s eta 0:00:08
   -------------------- ------------------- 21.2/40.9 MB 2.8 MB/s eta 0:00:07
   --------------------- ------------------ 21.8/40.9 MB 2.8 MB/s eta 0:00:07
   --------------------- ------------------ 22.3/40.9 MB 2.8 MB/s eta 0:00:07
   ---------------------- ----------------- 22.8/40.9 MB 2.8 MB/s eta 0:00:07
   ---------------------- ----------------- 23.3/40.9 MB 2.8 MB/s eta 0:00:07
   ----------------------- ---------------- 23.9/40.9 MB 2.8 MB/s eta 0:00:07
   ----------------------- ---------------- 24.1/40.9 MB 2.8 MB/s eta 0:00:07
   ------------------------ --------------- 24.9/40.9 MB 2.8 MB/s eta 0:00:06
   ------------------------- -------------- 25.7/40.9 MB 2.8 MB/s eta 0:00:06
   ------------------------- -------------- 26.0/40.9 MB 2.8 MB/s eta 0:00:06
   ------------------------- -------------- 26.5/40.9 MB 2.7 MB/s eta 0:00:06
   -------------------------- ------------- 27.0/40.9 MB 2.7 MB/s eta 0:00:06
   -------------------------- ------------- 27.5/40.9 MB 2.7 MB/s eta 0:00:05
   --------------------------- ------------ 28.0/40.9 MB 2.7 MB/s eta 0:00:05
   ---------------------------- ----------- 28.8/40.9 MB 2.7 MB/s eta 0:00:05
   ---------------------------- ----------- 29.4/40.9 MB 2.7 MB/s eta 0:00:05
   ----------------------------- ---------- 29.9/40.9 MB 2.7 MB/s eta 0:00:05
   ----------------------------- ---------- 30.7/40.9 MB 2.7 MB/s eta 0:00:04
   ------------------------------ --------- 30.9/40.9 MB 2.7 MB/s eta 0:00:04
   ------------------------------ --------- 31.7/40.9 MB 2.7 MB/s eta 0:00:04
   ------------------------------- -------- 32.5/40.9 MB 2.8 MB/s eta 0:00:04
   -------------------------------- ------- 33.3/40.9 MB 2.8 MB/s eta 0:00:03
   --------------------------------- ------ 34.1/40.9 MB 2.8 MB/s eta 0:00:03
   --------------------------------- ------ 34.6/40.9 MB 2.8 MB/s eta 0:00:03
   ---------------------------------- ----- 35.1/40.9 MB 2.8 MB/s eta 0:00:03
   ---------------------------------- ----- 35.7/40.9 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 36.2/40.9 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 36.7/40.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 37.5/40.9 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 37.7/40.9 MB 2.7 MB/s eta 0:00:02
   ------------------------------------- -- 38.5/40.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 39.3/40.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 39.8/40.9 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  40.6/40.9 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 40.9/40.9 MB 2.8 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0

In [2]:
# Step 0: Understand the problem and the company
# Step 1: Import the data

import pandas as pd

df = pd.read_csv("clientes.csv")

display(df)

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,alto_gasto_pagamento_medio,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

In [12]:
# Step 2: Prepare the database for the AI

from sklearn.preprocessing import LabelEncoder

# print(df.info())

print({a for a in df["profissao"]})

codifier_prof = LabelEncoder()
codifier_cred = LabelEncoder()
codifier_pag = LabelEncoder()

df["profissao"] = codifier_prof.fit_transform(df["profissao"])
df["mix_credito"] = codifier_cred.fit_transform(df["mix_credito"])
df["comportamento_pagamento"] = codifier_pag.fit_transform(df["comportamento_pagamento"])

print(df.info())

display(df)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int64
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int64
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int64
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(10), object(1)
memory usage: 19.1+ MB
None

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,1,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,3,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,5,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,2,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,4,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,2,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,2,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,11,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,0,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,2,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,11,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,0,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,11,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,3,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,2,393.673696,Poor,1,0,0,0,1

In [13]:
# Divide in X and Y
# X (use to predict) -> all other columns
# Y (predict) -> score_credito

y = df["score_credito"]
x = df.drop(columns=["score_credito", "id_cliente"])

# Split data into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, train_size=0.7)

In [22]:
# Step 3: Create model -> predict credit score

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# RandomForest
# forest_model = RandomForestClassifier()
# RandomForest upgraded with parameters
forest_model = RandomForestClassifier(n_estimators=200, random_state=42)
# KNN
# knn_model = KNeighborsClassifier()
# KNN upgraded with parameters
knn_model = KNeighborsClassifier(n_neighbors=5, weights='distance')

# training models
forest_model.fit(x_train, y_train)
knn_model.fit(x_train, y_train)

KNeighborsClassifier(weights='distance')

In [28]:
# Step 4: Choose the best model
from sklearn.metrics import accuracy_score

# Predicts
predict_forest = forest_model.predict(x_test)
predict_knn = knn_model.predict(x_test)

# Accuracy
display(accuracy_score(y_test, predict_forest)) # Best for now with 82.66%
display(accuracy_score(y_test, predict_knn))    # 75.82%

0.8266333333333333

0.7582666666666666

In [29]:
# Step 5: Make new predicts

# New clients
new_df = pd.read_csv("novos_clientes.csv")

new_df["profissao"] = codifier_prof.fit_transform(new_df["profissao"])
new_df["mix_credito"] = codifier_cred.fit_transform(new_df["mix_credito"])
new_df["comportamento_pagamento"] = codifier_pag.fit_transform(new_df["comportamento_pagamento"])

predict_forest = forest_model.predict(new_df)
predict_knn = knn_model.predict(new_df)

display(predict_forest)
display(predict_knn)

display(new_df)

array(['Poor', 'Standard', 'Standard'], dtype=object)

array(['Poor', 'Standard', 'Standard'], dtype=object)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,1,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,1,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,2,300.994163,0,0,0,0,1
2,2,48.0,1,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,0,345.081577,0,1,0,1,0